### ISSUE TITLE
incorrect formatting with rmd_shot

### ISSUE THREAD

**Issue by RKonstantinR** [rstudio/webshot2#55]
I created a quarto document using callout blocks and grid. 

When I render this document in rstudio the formatting is displayed correctly:
![изображение](https://github.com/rstudio/webshot2/assets/38781076/dad64f77-4b23-4b3a-bc15-f445797b8ce0)

But when I use rmdshot formatting is not displayed correctly:
![изображение](https://github.com/rstudio/webshot2/assets/38781076/bb8d265b-454c-4f4d-9102-2894dce75a9a)

Is there a way to fix this?

Quarto doc:
``````
---
title: "repex"
format:
  html:
    embed-resources: true
    page-layout: full
editor: visual
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(echarts4r)
library(tibble)

```

::: grid
::: g-col-2
::: {.callout-note icon="false"}
## one

1
:::
:::

::: g-col-2
::: {.callout-note icon="false"}
## two

2
:::
:::

::: g-col-2
::: {.callout-note icon="false"}
## three

3
:::
:::

::: g-col-2
::: {.callout-note icon="false"}
## four

4
:::
:::

::: g-col-2
::: {.callout-note icon="false"}
## five

5
:::
:::

::: g-col-2
::: {.callout-note icon="false"}
## six

6
:::
:::
:::

::: grid
::: g-col-2
::: border
::: ticker_name
TEXT
:::

::: board_name
SUBTEXT
:::
:::

::: {.callout-tip appearance="minimal"}
foo: bar

foo: bar

foo: bar
:::
:::

::: g-col-10
```{r, echo=FALSE, message=FALSE, warning=FALSE}

plot(mtcars$cyl)

```
:::
:::

``````

R script:
```
library(webshot2)

webshot2::rmdshot("test.qmd", file = "tst.png")
```

**Comment by gadenbuie** [comment]
The problem is that `rmdshot()` is specifically tied to the R Markdown format. In other words, it calls `rmarkdown::render()` or `rmarkdown::run()` on the input document. So in this case, even though you have a `.qmd` file, it's being processed with `rmarkdown` instead of `quarto`.

You can get around this by first rendering the document to HTML and then calling `webshot()` on that document. I'll open a new issue to track a feature request for `webshot2::qmdshot()`.

```r
# install.packages("quarto")

quarto::quarto_render("test.qmd")
webshot2::webshot("test.html", file = "test.png")
```

![test](https://github.com/rstudio/webshot2/assets/5420529/c54fe80c-7b0b-4bbd-997f-abb00b247f9c)

**Comment by RKonstantinR** [comment]
Workaround works as expected, thanks for the help!
